
DROP TABLE IF EXISTS SALES_POSITIONS_S3;

CREATE EXTERNAL TABLE SALES_POSITIONS_S3 (
  SALES_ID    DECIMAL(18,0),
  POSITION_ID DECIMAL(9,0),
  ARTICLE_ID  DECIMAL(9,0),
  AMOUNT      DECIMAL(9,0),
  PRICE       DECIMAL(9,2),
  VOUCHER_ID  DECIMAL(9,0),
  CANCELED    BOOLEAN
)
STORED AS PARQUET
LOCATION 's3://exa-mo-frankfurt/retail/sales_positions/'
TBLPROPERTIES ("parquet.compression"="SNAPPY");


DROP TABLE IF EXISTS SALES_S3;

CREATE EXTERNAL TABLE SALES_S3 (
  SALES_ID INTEGER,
  SALES_DATE DATE,
  SALES_TIMESTAMP TIMESTAMP,
  PRICE DECIMAL(9,2),
  MONEY_GIVEN DECIMAL(9,2),
  RETURNED_CHANGE DECIMAL(9,2),
  LOYALTY_ID INTEGER,
  MARKET_ID SMALLINT,
  TERMINAL_ID SMALLINT,
  EMPLOYEE_ID SMALLINT,
  TERMINAL_DAILY_SALES_NR SMALLINT
)
STORED AS PARQUET
LOCATION 's3://exa-mo-frankfurt/retail/sales/'
TBLPROPERTIES ("parquet.compression"="SNAPPY");

DROP TABLE IF EXISTS SALES_POSITIONS;

CREATE TABLE SALES_POSITIONS (
  SALES_ID    DECIMAL(18,0),
  POSITION_ID DECIMAL(9,0),
  ARTICLE_ID  DECIMAL(9,0),
  AMOUNT      DECIMAL(9,0),
  PRICE       DECIMAL(9,2),
  VOUCHER_ID  DECIMAL(9,0),
  CANCELED    BOOLEAN
)
STORED AS PARQUET
TBLPROPERTIES ("parquet.compression"="SNAPPY");


DROP TABLE IF EXISTS SALES;

CREATE TABLE SALES (
  SALES_ID INTEGER,
  SALES_DATE DATE,
  SALES_TIMESTAMP TIMESTAMP,
  PRICE DECIMAL(9,2),
  MONEY_GIVEN DECIMAL(9,2),
  RETURNED_CHANGE DECIMAL(9,2),
  LOYALTY_ID INTEGER,
  MARKET_ID SMALLINT,
  TERMINAL_ID SMALLINT,
  EMPLOYEE_ID SMALLINT,
  TERMINAL_DAILY_SALES_NR SMALLINT
)
STORED AS PARQUET
TBLPROPERTIES ("parquet.compression"="SNAPPY");

INSERT INTO sales_positions SELECT * FROM sales_positions_s3;

INSERT INTO sales SELECT * FROM sales_s3;
