
DROP TABLE IF EXISTS SALES_POSITIONS_S3;

CREATE EXTERNAL TABLE SALES_POSITIONS_S3 (
  SALES_ID    BIGINT,
  POSITION_ID INT,
  ARTICLE_ID  INT,
  AMOUNT      INT,
  PRICE       DOUBLE,
  VOUCHER_ID  INT,
  CANCELED    BOOLEAN
)
STORED AS PARQUET
LOCATION 's3://exa-mo-frankfurt/retail_parquet/sales_positions/'
TBLPROPERTIES ("parquet.compression"="SNAPPY");


DROP TABLE IF EXISTS SALES_S3;

CREATE EXTERNAL TABLE SALES_S3 (
  SALES_ID                BIGINT,
  SALES_DATE              DATE,
  SALES_TIMESTAMP         TIMESTAMP,
  PRICE                   DOUBLE,
  MONEY_GIVEN             DOUBLE,
  RETURNED_CHANGE         DOUBLE,
  LOYALTY_ID              BIGINT,
  MARKET_ID               INT,
  TERMINAL_ID             INT,
  EMPLOYEE_ID             INT,
  TERMINAL_DAILY_SALES_NR INT
)
STORED AS PARQUET
LOCATION 's3://exa-mo-frankfurt/retail_parquet/sales/'
TBLPROPERTIES ("parquet.compression"="SNAPPY");


DROP TABLE IF EXISTS SALES_POSITIONS;

CREATE TABLE SALES_POSITIONS (
  SALES_ID    BIGINT,
  POSITION_ID INT,
  ARTICLE_ID  INT,
  AMOUNT      INT,
  PRICE       DOUBLE,
  VOUCHER_ID  INT,
  CANCELED    BOOLEAN
)
STORED AS PARQUET
TBLPROPERTIES ("parquet.compression"="SNAPPY");


DROP TABLE IF EXISTS SALES;

CREATE TABLE SALES (
  SALES_ID                BIGINT,
  SALES_DATE              DATE,
  SALES_TIMESTAMP         TIMESTAMP,
  PRICE                   DOUBLE,
  MONEY_GIVEN             DOUBLE,
  RETURNED_CHANGE         DOUBLE,
  LOYALTY_ID              BIGINT,
  MARKET_ID               INT,
  TERMINAL_ID             INT,
  EMPLOYEE_ID             INT,
  TERMINAL_DAILY_SALES_NR INT
)
STORED AS PARQUET
TBLPROPERTIES ("parquet.compression"="SNAPPY");

INSERT INTO sales_positions SELECT * FROM sales_positions_s3;

INSERT INTO sales SELECT * FROM sales_s3;
